-- The shared trip. One row per trip, holding the whole plan document, which is
-- how the app already stores it locally.
create table public.trips (
  code       text primary key,
  doc        jsonb       not null,
  rev        integer     not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- The trip code is the only key. Nobody reaches the table directly: row level
-- security is on with no policies, so a client using the publishable key sees
-- nothing and cannot list what codes exist. The two functions below are the
-- only way in, and each one needs the code up front.
alter table public.trips enable row level security;
revoke all on table public.trips from anon, authenticated;

create function public.trip_pull(p_code text)
returns table (doc jsonb, rev integer, updated_at timestamptz)
language sql
security definer
set search_path = public, pg_temp
as $$
  select t.doc, t.rev, t.updated_at
    from public.trips t
   where t.code = p_code;
$$;

-- Accept a newer revision and reject a stale one, handing the current copy back
-- so the caller can settle rather than overwrite blindly.
create function public.trip_push(p_code text, p_doc jsonb, p_rev integer)
returns table (doc jsonb, rev integer, updated_at timestamptz, accepted boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  saved public.trips;
begin
  -- Codes are generated by the app with 128 bits of randomness. Refusing short
  -- ones keeps the open endpoint from being used to make junk rows.
  if p_code is null or length(p_code) < 32 then
    raise exception 'invalid trip code';
  end if;
  if p_doc is null then
    raise exception 'missing trip document';
  end if;

  insert into public.trips as t (code, doc, rev, updated_at)
       values (p_code, p_doc, p_rev, now())
  on conflict (code) do update
          set doc = excluded.doc, rev = excluded.rev, updated_at = now()
        where t.rev < excluded.rev
    returning * into saved;

  if found then
    return query select saved.doc, saved.rev, saved.updated_at, true;
  else
    return query select t.doc, t.rev, t.updated_at, false
                   from public.trips t
                  where t.code = p_code;
  end if;
end;
$$;

grant execute on function public.trip_pull(text) to anon, authenticated;
grant execute on function public.trip_push(text, jsonb, integer) to anon, authenticated;
